name: bluetooth_20220230
description: A new Flutter project.

# Prevent accidental publication to pub.dev
publish_to: 'none'

# Define the version and build number
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.31.15

  # Add the Cupertino Icons font for iOS-style icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Add recommended lints for better coding practices
  flutter_lints: ^2.0.3

# Flutter-specific configurations
flutter:
  uses-material-design: true